# Generated by Django 2.1.7 on 2019-03-28 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('venue', models.TextField()),
                ('reservation', models.CharField(max_length=10, null=True)),
                ('reserved', models.CharField(max_length=10, null=True)),
                ('statedate', models.DateTimeField(null=True)),
                ('enddate', models.DateTimeField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
                ('rating', models.CharField(max_length=10, null=True)),
                ('organisername', models.CharField(max_length=30, null=True)),
                ('organiseremail', models.CharField(max_length=100, null=True)),
                ('organiserphone', models.CharField(max_length=12, null=True)),
                ('banner1', models.ImageField(default='default.jpg', null=True, upload_to='banners')),
                ('banner2', models.ImageField(default='default.jpg', null=True, upload_to='banners')),
                ('speaker1name', models.CharField(max_length=30, null=True)),
                ('speaker2name', models.CharField(max_length=30, null=True)),
                ('speaker1bio', models.TextField(null=True)),
                ('speaker2bio', models.TextField(null=True)),
                ('speaker1pics', models.ImageField(default='default.jpg', null=True, upload_to='speaker_pics')),
                ('speaker2pics', models.ImageField(default='default.jpg', null=True, upload_to='speaker_pics')),
                ('tags', models.CharField(max_length=50, null=True)),
                ('description1', models.TextField(null=True)),
                ('description2', models.TextField(null=True)),
                ('moreinfo', models.TextField(null=True)),
                ('postedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
